controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_sensor_broadcaster:
      type: ur_controllers/ForceTorqueStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data


joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_position: 0.002
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.3, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.3, goal: 0.1 }
      elbow_joint: { trajectory: 0.3, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.3, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.3, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.3, goal: 0.1 }
